{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trivia.postgres.fullname" . }}
  labels:
    {{- include "trivia.postgres.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "trivia.postgres.selectorLabels" . | nindent 4 }}
---
{{- if .Values.postgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "trivia.postgres.fullname" . }}-data
  labels:
    {{- include "trivia.postgres.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.postgres.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
  {{- if .Values.postgres.persistence.storageClass }}
  storageClassName: {{ .Values.postgres.persistence.storageClass | quote }}
  {{- end }}
---
{{- end }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "trivia.postgres.fullname" . }}
  labels:
    {{- include "trivia.postgres.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "trivia.postgres.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "trivia.postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "trivia.postgres.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
        imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
        ports:
        - name: postgres
          containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres.user | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.postgres.database | quote }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "trivia.secretName" . }}
              key: POSTGRES_PASSWORD
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "{{ .Values.postgres.user }}"]
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "{{ .Values.postgres.user }}"]
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          {{- toYaml .Values.postgres.resources | nindent 10 }}
      volumes:
      - name: data
        {{- if .Values.postgres.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "trivia.postgres.fullname" . }}-data
        {{- else }}
        emptyDir: {}
        {{- end }}
{{- end }}
